### ISSUE TITLE
Nodepool import not working unmarshal error on extendParam 

### ISSUE THREAD

**Issue by Tobeje** [opentelekomcloud/terraform-provider-opentelekomcloud#2050]
# Terraform provider version

`provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.32.2`

# Affected Resource(s)

`opentelekomcloud_cce_node_pool_v3`

# Steps to Reproduce

1. Create a nodepool manually with the following config
    EulerOS 2.9
    root_volume 40GB SSD
    data_volumes 200GB SSD
2. Use `terraform import opentelekomcloud_cce_node_pool_v3.pool_1 cluster_id/node_pool_id`

# Expected Behavior

Import the nodepool to the terraform state

# Actual Behavior

Error occurs:
```
Error: CCE Node Pool: error extracting {"kind":"NodePool","apiVersion":"v3","metadata":{"name":"autoscaler-pool-euler","uid":"xxx","creationTimestamp":"2022-09-30 11:56:30.20812 +0000 UTC","updateTimestamp":"2023-01-16 07:42:17.651489 +0000 UTC","annotations":{"os.architecture":"amd64"}},"spec":{"initialNodeCount":5,"type":"vm","nodeTemplate":{"flavor":"s2.xlarge.8","az":"eu-de-01","os":"EulerOS 2.9","login":{"sshKey":"xxx","userPassword":{}},"rootVolume":{"volumetype":"SSD","size":40},"dataVolumes":[{"volumetype":"SSD","size":200,"extendParam":{"useType":"docker"}}],"publicIP":{"eip":{"bandwidth":{}}},"nodeNicSpec":{"primaryNic":{"subnetId":"xxx"}},"billingMode":0,"k8sTags":{"cce.cloud.com/cce-nodepool":"autoscaler-pool-euler"},"runtime":{},"partition":"center","extendParam":{"DockerLVMConfigOverride":"dockerThinpool=vgpaas/90%VG;kubernetesLV=vgpaas/10%VG;diskType=evs;lvType=linear","maxPods":110}},"autoscaling":{"enable":true,"minNodeCount":1,"maxNodeCount":29,"scaleDownCooldownTime":5,"priority":1},"nodeManagement":{}},"status":{"currentNode":5,"deletingNode":0,"creatingNode":0,"phase":"","conditions":[{"type":"Scalable","status":"True","lastProbeTime":"2022-09-30T11:56:30.20812Z","lastTransitTime":"2022-09-30T11:56:30.20812Z"}]}} into *nodepools.NodePool: json: cannot unmarshal object into Go struct field VolumeSpec.spec.nodeTemplate.dataVolumes.extendParam of type string

```

**Comment by artem-lifshits** [comment]
Hello @Tobeje this is fixed in latest provider release, please check.

**Comment by Tobeje** [comment]
Hello @artem-lifshits,
sorry for my late response, the error still occurs... Im using the version `opentelekomcloud/opentelekomcloud v1.32.2`.
