### ISSUE TITLE
[FG] instance re-created without any change in reserved instances & tactics

### ISSUE THREAD

**Issue by cboelle** [opentelekomcloud/terraform-provider-opentelekomcloud#3020]
Bug, when re-apply /after success creating function. reserved instance is detected to be dropped/created again.
Apply in 2nd attempt will drop reserved instance without any need.

# Terraform provider version
v1.36.40

# Affected Resource(s)

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_fgs_function_v2" "api_demo_page_generator" {
  name                = "api-demo-page-generator"
  description         = "Deliver dynamic html pages"
  runtime             = "Java17"
  app                 = "default"
  memory_size         = 512
  timeout             = 20
  code_type           = "obs"
  code_url            = var.fg_source_obs_url
  agency              = "dlg_fg_agency"
  vpc_id              = var.vpc_id
  network_id          = var.network_id
  handler             = "com.opentelekomcloud.refstack.api.APIGPageGenerator.handleRequest"
  initializer_handler = "com.opentelekomcloud.refstack.api.APIGPageGenerator.initializer"
  initializer_timeout = 10
  log_group_id        = var.api_ref_stack.lts_group_id
  log_group_name      = var.api_ref_stack.lts_group_name
  log_topic_id        = opentelekomcloud_lts_stream_v2.lts_stream_functions.id
  log_topic_name      = opentelekomcloud_lts_stream_v2.lts_stream_functions.stream_name

  user_data = jsonencode({
    "cache.url"             = var.api_ref_stack.dcs_cache_url
    "obs.bucket"            = var.obs_bucket
    "apig.domain"           = var.api_ref_stack.api_domain
    "apig.auth.user"        = var.api_ref_stack.api_user_dynamic
    "apig.endpoint.weather" = "${var.api_ref_stack.api_domain}/${var.api_ref_stack.resource_path_weather}"
    "apig.endpoint.status"  = "${var.api_ref_stack.api_domain}/${var.api_ref_stack.resource_path_status}"
    "apig.endpoint.audit"   = "${var.api_ref_stack.api_domain}/${var.api_ref_stack.resource_path_audit}"
  })

  tags = {
    "asset-id"      = "K-2025-FGG83",
    "billing-bu"    = "Research",
    "billing-class" = "live-de"
    "app-group"     = "java-hg1-fg@api-demo"
  }
  reserved_instances{
    qualifier_name = "latest"
    qualifier_type = "version"
    idle_mode = false
    count = 1
    tactics_config {
      cron_configs {
        name         = "fg-scheduler-tactics-page-generator"
        count        = 1
        cron         = "0 */10 * * * ?"
        start_time   = 1751746345   #date handling could be nicer
        expired_time = 1783282345   #date handling could be nicer
      }
    }
  }
}
```

# Debug Output/Panic Output
1st try - Function runs without VPC binding, but new attribute "network_type    = "NON-VPC" is generated during verify
```hcl
 # opentelekomcloud_apigw_api_v2.hg1_api_page_generator will be updated in-place
  ~ resource "opentelekomcloud_apigw_api_v2" "hg1_api_page_generator" {
        id                              = "d0fa7624dbe8463585e589b1f82d158a"
        name                            = "bdp-page-generator"
        tags                            = [
            "API-Demo",
        ]
        # (14 unchanged attributes hidden)

      ~ func_graph {
          + network_type    = "NON-VPC"
            # (4 unchanged attributes hidden)
        }
    }
```
2nd try
```hcl
  # opentelekomcloud_fgs_function_v2.api_demo_page_generator will be updated in-place
  ~ resource "opentelekomcloud_fgs_function_v2" "api_demo_page_generator" {
        id                    = "urn:fss:eu-de:ae050143781c4ab6a130522e5f2d30c1:function:default:api-demo-page-generator:latest"
        name                  = "api-demo-page-generator"
        tags                  = {
            "app-group"     = "java-hg1-fg@api-demo"
            "asset-id"      = "K-2025-FGG83"
            "billing-bu"    = "Research"
            "billing-class" = "live-de"
        }
        # (27 unchanged attributes hidden)

      + reserved_instances {
          + count          = 1
          + idle_mode      = false
          + qualifier_name = "latest"
          + qualifier_type = "version"

          + tactics_config {
              + cron_configs {
                  + count        = 1
                  + cron         = "0 */10 * * * ?"
                  + expired_time = 1783282345
                  + name         = "fg-scheduler-tactics-page-generator"
                  + start_time   = 1751746345
                }
            }
        }

        # (1 unchanged block hidden)
    }
```
# Steps to Reproduce

1. `terraform apply` multiple times

# Expected Behavior
Reserved instances are just deleted and re-created when changes are done

# Actual Behavior
With every apply instances are deleted and created

**Comment by artem-lifshits** [comment]
Hello @cboelle issue is fixed in latest release, please check.

**Comment by cboelle** [comment]
@artem-lifshits I have updated provider to Terraform v1.6.5
on windows_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.43

But problem still persists

**Comment by artem-lifshits** [comment]
@cboelle does the issue occur on an old FuncGraph or a new one?
For old funcgraph issue can't be fixed but new ones shouldn't have it.

**Comment by cboelle** [comment]
@artem-lifshits Thanks for the tip. I deleted all functions and created them from scratch... some interesting finding: I have multiple functions with 2 reserved instances (one for each) during change detection tf assumes tactics config from another function to be linked to first function:

```
# opentelekomcloud_fgs_function_v2.api_demo_health_check will be updated in-place
  ~ resource "opentelekomcloud_fgs_function_v2" "api_demo_health_check" {
      ~ encrypted_user_data   = (sensitive value)
        id                    = "urn:fss:eu-de:ae050143781c4ab6a130522e5f2d30c1:function:default:api-demo-health-check:latest"
        name                  = "api-demo-health-check"
        tags                  = {
            "app-group"     = "java-hg1-fg@api-demo"
            "asset-id"      = "K-2025-FGX5G"
            "billing-bu"    = "Research"
            "billing-class" = "live-de"
        }
        # (25 unchanged attributes hidden)

      - reserved_instances {
          - count          = 1 -> null
          - idle_mode      = false -> null
          - qualifier_name = "latest" -> null
          - qualifier_type = "version" -> null

          - tactics_config {
              - cron_configs {
                  - count        = 1 -> null
                  - cron         = "0 */10 * * * ?" -> null
                  - expired_time = 1783282345 -> null
                  - name         = "fg-scheduler-tactics-page-generator" -> null
                  - start_time   = 1751746345 -> null
                }
            }
        }
      - reserved_instances {
          - count          = 1 -> null
          - idle_mode      = true -> null
          - qualifier_name = "latest" -> null
          - qualifier_type = "version" -> null

          - tactics_config {
              - cron_configs {
                  - count        = 1 -> null
                  - cron         = "0 */10 * * * ?" -> null
                  - expired_time = 1783282345 -> null
                  - name         = "fg-scheduler-tactics-key-authorizer" -> null
                  - start_time   = 1751746345 -> null
                }
            }
        }

        # (1 unchanged block hidden)
    }
`

**Comment by cboelle** [comment]
@artem-lifshits for me the behavior looks like this: when having multiple function like 5 without reserved instances and 1 with reserved instances. It detects change to remove the reserved instance (because of those functions without reserved instances). When having script only with one function and one reserved instance it seems fine. 
I assume reserved instance is not bound to the function it-self, so other functions without reserved instance drop it. Maybe reserved instance id needs to be combined with function id to build a unique object.
Hope this helps :)

**Comment by cboelle** [comment]
@artem-lifshits Could you already verify the issue?
