### ISSUE TITLE
Issue provisioning CCE cluster. E.CFE.4000201

### ISSUE THREAD

**Issue by raypettersen** [opentelekomcloud/terraform-provider-opentelekomcloud#493]
### Terraform Version
Latest version.

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_cce_cluster_v3

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  name                   = var.deployment_name
  cluster_type           = var.cce_type
  flavor_id              = var.flavor_id_cluster
  vpc_id                 = var.vpc_id
  subnet_id              = var.subnet_id
  container_network_type = "overlay_l2"
}

resource "opentelekomcloud_cce_node_v3" "node" {
  count             = var.nodecount
  cluster_id        = opentelekomcloud_cce_cluster_v3.cluster.id
  name              = "${var.deployment_name}0${count.index + 1}"
  flavor_id         = var.flavor_id_node
  iptype            = "5_bgp"
  eip_count         = 0
  availability_zone = var.azs[count.index]
  key_pair          = var.key_name

  root_volume {
    size       = var.root_volume
    volumetype = "SATA"
  }

  sharetype      = "PER"
  bandwidth_size = 100

  data_volumes {
    size       = var.data_volume
    volumetype = "SATA"
  }
  # This is according to doc but forces node-redeploy on each run.
  # max_pods = var.max_pods
}

```

### Expected Behavior
Expecting CCE to be provisioned accordingly.

### Actual Behavior
```TestTerraform 2020-05-06T11:08:04+02:00 command.go:168: Error: Error creating opentelekomcloud Cluster: Bad request with: [POST https://cce.eu-de.otc.t-systems.com/api/v3/projects/16614f0000ea4576a0a47c55a3bdfd75/clusters], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"Need authorize CCE to operate user resources","errorCode":"E.CFE.4000201","reason":"Request body invalid"}```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by outcatcher** [comment]
You need to authorize CCE on the console first if you haven't done it yet. That should fix the issue.

**Comment by raypettersen** [comment]
We did just that, in the tenant itself and in the "staging project". We're still seeing the error. We also tried the RBAC authentication_type and that seems to be returning that the authentication_type is invalid.

```authentication_mode = "rbac"```

```TestTerraform 2020-05-06T12:05:45+02:00 command.go:168: Error: Error creating opentelekomcloud Cluster: Bad request with: [POST https://cce.eu-de.otc.t-systems.com/api/v3/projects/16614f0000ea4576a0a47c55a3bdfd75/clusters], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"cluster authentication mode is invalid","errorCode":"E.CFE.4000201","reason":"Request body invalid"}```

**Comment by outcatcher** [comment]
RBAC auth mode works for me like that:
```hcl2
resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  name                   = "cluster-test"
  cluster_type           = "VirtualMachine"
  container_network_type = "overlay_l2"
  flavor_id              = "cce.s1.small"
  authentication_mode    = "rbac"
  subnet_id              = opentelekomcloud_vpc_subnet_v1.subnet.id
  vpc_id                 = opentelekomcloud_vpc_v1.vpc.id
}
```

**Comment by raypettersen** [comment]
Thanks @outcatcher , git our staging running with rbac (which is odd because we tried that earlier and just got a 500 from the APIs). However we'd like to go with default authentication_type (x509) but that's throwing an error.

```TestTerraform 2020-05-06T12:44:35+02:00 command.go:168: Error: Error creating opentelekomcloud Cluster: Bad request with: [POST https://cce.eu-de.otc.t-systems.com/api/v3/projects/16614f0000ea4576a0a47c55a3bdfd75/clusters], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"cluster authentication mode is invalid","errorCode":"E.CFE.4000201","reason":"Request body invalid"}```

Any tips on what the cause could be or how to proceed?

**Comment by outcatcher** [comment]
As far as I can see, only cluster versions v1.11 supports x509 auth. Default version in OTC is `v1.13.10-rc0`, so if you want to use x509, please use the following config (this works for me, at least):
```hcl2
...
  cluster_version        = "v1.11.7-r2"
  authentication_mode    = "x509"
...
```
Sorry for the documentation inconsistance.

**Comment by outcatcher** [comment]
Internal OTC issue created from outdated OTC documentation.
#494 created for provider documentation.

**Comment by raypettersen** [comment]
Thanks, I had a suspicion that version might be relevant. 
Is rbac the way forward when using K8s in OTC? So we should rewrite our modules for that purpose?

**Comment by outcatcher** [comment]
RBAC is recommended auth method in [API documentation](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0236.html)
In OTC CCE [user guide](https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0028.html) there is no mention of `x509`
Latest versions of k8s also don't support `x509` method

So I suppose, RBAC is a better option for future usage

**Comment by raypettersen** [comment]
Thank you, we're moving ahead with rbac then. This issue can be closed, and thanks a lot for the quick response and helpful replies.
